import './sass/index.scss';
import './js/storage/localstorage';
// import './js/modal-window';
import './js/restAPI/restAPI';
import './js/pagination-home/pagination-home';
// import './js/pagination-library';
import './js/render-cards';
import './js/search/search';
import './js/theme';
import './js/fetch-popular';
import './js/slider';
import './js/modal-window/open-modal';
