import './sass/index.scss';
// import './js/local-storage/';
// import './js/modal-window';
import './js/render-cards';
import './js/restAPI/restAPI';
// import './js/pagination-home/pagination-home';
// import './js/refs/refs';
import './js/theme';
import './js/search/search';
import './js/modal-window/open-modal';